---
- name: enable web server
  hosts: servera
  remote_user: devops
  tasks:
  - name: install stuff
    ansible.builtin.dnf:
      name:
      - httpd
      - firewalld
  - name: correct index.html is present
    ansible.builtin.copy:
      content: "This is my web server...\n"
      dest: /var/www/html/index.html
  - name: enable webserver
    ansible.builtin.service: 
      name: httpd
      state: started
      enabled: true
  - name: enable firewall
    ansible.builtin.service:
      name: firewalld
      state: started
      enabled: true
  - name: open service in firewall
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes

- name: test webserver access
  hosts: localhost
  become: no
  tasks:
  - name: test webserver access
    ansible.builtin.uri:
      url: http://servera
      return_content: yes
      status_code: 200

