---
- name: copy multiline test
  hosts: servera
  tasks:
  - name: copy text
    ansible.builtin.copy:
      content: |
        line 1
        line 2
      dest: /tmp/multiline1.txt

  - name: copy more text
    ansible.builtin.copy:
      content: >
        line 1
        line 2
      dest: /tmp/multiline2.txt
   
