---
- name: install start and enable httpd
  hosts: web
  tasks:
  - name: httpd package is present
    ansible.builtin.dnf:
      name: httpd
      state: present
  - name: correct index.html is present
    ansible.builtin.copy:
      content: "This is my web server...\n"
      dest: /var/www/html/index.html
  - name: start and enable service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes

- name: test httpd accessibility
  hosts: localhost
  become: no
  tasks:
  - name: test httpd access
    ansible.builtin.uri:
      url: http://servera
