---
- name: configure web services
  hosts: web
  tasks:
  - name: this is the {{ web_package }} package
    ansible.builtin.debug:
      msg: "Installing {{ web_package }}"
  - name: this is the {{ web_service }} service
    ansible.builtin.debug:
      msg: "Starting {{ web_service }}"
  - name: this is the {{ web_port }} port
    ansible.builtin.debug:
      msg: "Opening {{ web_port }} port"
