---
- name: show dictionary also known as hash
  hosts: servera
  vars_files:
  - vars/users-dictionary
  tasks:
  - name: print dictionary values
    ansible.builtin.debug:
      msg: "User {{ users['linda']['username'] }} has homedirectory {{ users['linda']['homedir'] }} and shell {{ users['linda']['shell']  }}"
