---
- name: create a user using a variable
  hosts: servera
  vars:
    user: lisa
  tasks:
    - name: create a user {{ user }} on host {{ ansible_hostname }} 
      ansible.builtin.user:
        name: "{{ user }}"
