---
- name: create a user with vaulted variables
  hosts: servera
  vars_files:
    - secrets.yml
  tasks:
  - name: creating user
    ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ pwhash }}"
