---
- name: test register
  hosts: all
  tasks:
    - ansible.builtin.shell: cat /etc/passwd
      register: passwd_contents
    - ansible.builtin.debug:
        msg: "{{ passwd_contents }}"
    - ansible.builtin.debug: 
        msg: passwd contains user lisa
      when: passwd_contents.stdout.find('lisa') != -1
