---
- name: conditionals test
  hosts: all
  tasks:
  - name: install vsftpd if sufficient memory available
    ansible.builtin.package:
      name: vsftpd
      state: latest
    when: ansible_facts['memory_mb']['real']['free'] > 50
