---
- name: Loop Register Test
  gather_facts: false
  hosts: localhost
  tasks:
  - name: Looping Echo Task
    ansible.builtin.shell: "echo This is my item: {{ item }}"
    loop:
      - one
      - two
    register: echo_results

  - name: Show stdout rom the previous task
    ansible.builtin.debug:
      msg: "STDOUT from previous task: {{ item['stdout'] }}"
    loop: "{{ echo_results['results'] }}"
