---
- name: using the file module
  hosts: servera
  tasks:
  - name: create directory
    ansible.builtin.file:
      path: /newdir
      owner: ansible
      group: ansible
      mode: 770
      state: directory
  - name: create file in that directory
    ansible.builtin.file:
      path: /newdir/newfile
      state: touch
  - name: show the new file
    ansible.builtin.stat:
      path: /newdir/newfile
    register: result
  - ansible.builtin.debug:
      msg: |
           This shows that newfile was created
           "{{ result }}"
  - name: removing everything again
    ansible.builtin.file:
      path: /newdir
      state: absent

