---
- name: include some roles
  hosts: all
  pre_tasks:
  - name: task run b4 roles
    notify: my handler
  roles:
  - role: role1
  - role: role2
  tasks:
  - name: task run after roles
    notify: my handler
  post_tasks:
  - name: task run after roles, tasks and handlers
    notify: my handler
  handlers:
  - name: my handler
...
