---
- name: install start and enable httpd
  hosts: all
  tasks:
  - name: install package
    ansible.builtin.dnf:
      name: httpd
      state: latest
  - name: start and enable service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
