---
- name: using assert to check if vgdata exists
  hosts: all
  tasks:
  - name: check if vgdata exists
    ansible.builtin.command: vgs vgdata
    register: vg_result
    ignore_errors: true
  - name: show vg_result variable
    ansible.builtin.debug:
      var: vg_result
    tags: [ never, debug ] 
  - name: print a message
    ansible.builtin.assert:
      that:
      - vg_result.rc == 0
      fail_msg: volume group not found
      success_msg: volume group was found
