---
- name: create a file
  hosts: all
  tasks:
  - ansible.builtin.file:
      path: /tmp/statfile
      state: touch
      owner: devops

- name: check file status
  hosts: all
  tasks:
  - ansible.builtin.stat:
      path: /tmp/statfile
    register: stat_out
  - ansible.builtin.fail: 
      msg: "/tmp/statfile file owner not as expected"
    when: stat_out.stat.pw_name != 'root'
