---
- name: install FTP to export repo
  hosts: servera
  tasks:
  - name: install FTP server
    ansible.builtin.dnf:
      name: 
      - vsftpd
      - createrepo_c
      state: latest
  - name: start FTP server
    ansible.builtin.service:
      name: vsftpd
      state: started
      enabled: yes
  - name: open firewall for FTP
    ansible.posix.firewalld:
      service: ftp
      state: enabled
      permanent: yes

- name: setup the repo directory
  hosts: servera
  tasks:
  - name: make directory
    ansible.builtin.file:
      path: /var/ftp/repo
      state: directory
  - name: download packages
    ansible.builtin.dnf:
      name: nmap
      download_only: yes
      download_dir: /var/ftp/repo
  - name: createrepo
    ansible.builtin.command: createrepo /var/ftp/repo
...
