--- 
- name: using package facts
  hosts: serverb
  vars:
    my_package: simple-agent
  tasks: 
  - name: install package
    ansible.builtin.dnf:
      name: "{{ my_package }}"
      state: present

  - name: update package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: show package facts for {{ my_package }}
    ansible.builtin.debug:
      var: ansible_facts['packages'][my_package]
    when: my_package in ansible_facts['packages']

