---
- name: create user with encrypted password
  hosts: serverb
  vars:
    password: "$6$mypassword$ypwXYJSRz53YfYqv5iO0pBsTw6EZBFoY8XuacnQMK4VWwFv3Ss/Fe7E3U3hEl8wJuKq/WaMghS5DgbS7bXQhD1"
  tasks:
  - name: create the user
    ansible.builtin.user: 
      name: anna
      password: "{{ password }}"

