---
- name: run an at task
  hosts: serverb
  tasks:
    - name: run command and write output to file
      ansible.posix.at:
        command: "date > /tmp/my-at-file"
        count: 5
        units: minutes
        unique: yes
        state: present
