---
- name: set default boot target
  hosts: serverb
  gather_facts: false
  tasks:
  - name: Get current systemd target
    ansible.builtin.command:
      cmd: systemctl get-default
      changed_when: false
    register: target

  - name: Set default systemd target
    ansible.builtin.command:
      cmd: systemctl set-default {{ systemd_target }}
    when: systemd_target not in target['stdout']

...
