---
- name: define variable according to diskname detected debug test
  hosts: all
  tasks:
  - ignore_errors: yes
    ansible.builtin.set_fact: 
      disk2name: vdb
    when: ansible_facts['devices']['vdb'] 

  - ignore_errors: yes
    ansible.builtin.set_fact:
      disk2name: nvme0n2
    when: ansible_facts['devices']['nvme0n2'] 
  
  - name: getting out if there is no second disk
    ansible.builtin.fail:
      msg: there is no second disk
    when: disk2name is not defined
  
  - name: showing this is only for hosts with a second disk
    ansible.builtin.debug:
      msg: continuing with {{ disk2name }} 

